server {
    listen 80;
    server_name _;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location /api {
        proxy_pass http://symfony:8000;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://react:80;
        proxy_set_header Host $host;
    }
}
